#!/bin/bash

# デフォルト値
TITLE="通知"
MESSAGE=""

# オプション解析
while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--title)
            TITLE="$2"
            shift 2
            ;;
        -m|--message)
            MESSAGE="$2"
            shift 2
            ;;
        *)
            if [ -z "$MESSAGE" ]; then
                MESSAGE="$1"
            fi
            shift
            ;;
    esac
done

# PowerShellで通知を表示
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe \
    "New-BurntToastNotification -Text \"$TITLE\", \"$MESSAGE\" -Sound Default"
