#!/bin/bash -e

OS=$(uname)
if [ "$OS" = "Darwin" ]; then
  :  # 何もしない場合の一時的なプレースホルダー
elif [ "$OS" = "Linux" ]; then
  if grep -q microsoft /proc/version; then
    WINDOWS_HOME=$(wslpath "$(wslvar USERPROFILE)")
    "$WINDOWS_HOME/AppData/Local/Programs/Zed/Zed.exe" "$@" >/dev/null 2>&1 &
  fi
fi
